server:
  port: 8100
  
# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false     #发现Eureka服务注册中心注册的服务提供者 （不进行注册消费者服务）
    service-url: 
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/